# Generated by Django 6.0.3 on 2026-03-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cro', models.CharField(max_length=20, unique=True, verbose_name='Registro CRO')),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('procedimento', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='agendado', max_length=10)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.paciente')),
            ],
        ),
    ]
