# Generated by Django 6.0.3 on 2026-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
