# Generated by Django 6.0.3 on 2026-03-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.procedimento'),
        ),
    ]
